### ISSUE TITLE
Plugin Integration/Extensibility Tracking Issue

### ISSUE THREAD

**Issue by smolck** [smolck/uivonim#7]
List of plugins/Neovim core features to look into providing (or to provide) a frontend UI for (by having an exposed Lua API with a default implementation for these plugins/features):

- [ ] [telescope.nvim](https://github.com/nvim-lua/telescope.nvim) (cc: @tjdevries, not possible yet?)
- [ ] [snippets.nvim](https://github.com/norcalli/snippets.nvim)
- [ ] Builtin LSP (see #1)

This is not an exhaustive list of course, should be edited as more are thought up, those are just the ones I can think of off the top of my head.

As for extensibility (again, not exhaustive, to be added to as ideas come up):

- [ ] Lua API for statusline (see #4)
